### PR TITLE
Bookmarks

### PR DESCRIPTION
**Pull request by cilestin**
Implements #8 
Implements #9 
bookmarks_example

I know it's not exactly as described in #8, because I opted to make manual bookmarking its own Tag & Action instead of some other system triggered by a new button on an event box. There were a couple reasons:
* Bookmarks, presumably, have a title (e.g. `Defeated the wyrm!`) and are tied to a Moment/Event. Feels very tag-like in that regard.
* Fewer steps to get a bookmark added. I can make it part of my writing flow instead of breaking into a different UI.
* Having bookmarks as an action means auto-bookmarking is just a matter of making some Tags add a BookmarkAction to the list on the Moment.

The thing I'm having a bit of a struggle with is how auto-bookmarking should be handled. Currently, I have it set so that an auto-bookmarking toggle determines whether to track them or not. Fairly straightforward until you start editing past events and turn the switch _on_ when it wasn't before.

Four options that I see:
1. Only let the edited Moment add any auto-bookmarks. (My original implementation)
1. The behavior remains like every other tag - you edited the history with the toggle on and, now every moment that may have created an auto-bookmark will do so as we re-apply actions. (The current behavior in my PR)
1. Always track auto-bookmarks, but make the toggle simply show/hide auto-bookmarks in the list.
1. Remove the toggle altogether, just let the filtering tabs make things easier to sort through.

I'm personally leaning toward option 4. The filtering has been very useful for me so far and since my manual bookmarks have their own filter, I don't really mind.

Sorry for the long-winded PR 😅

### CODE REVIEW

**Comment by SHiLLySiT** [comment]
@cilestin Thanks so much for implementing this hefty feature! Once this is merged I think I'm going to make a new release as there's a lot of new stuff you've added that I'm sure everyone would like to be using!

I completely agree with your reasons for adding bookmarks as tags instead of a separate toggling UI. I hadn't thought the feature completely through when I wrote #8, and after seeing how you implemented it, your solution is clearly the better one!

I agree with removing the toggle - its both frustrating to implement as a developer and I don't think its behavior will be clear to users. The filter tabs are a very elegant solution.

I have requests before merging:

- Removing the autobookmark toggle (as discussed above).
- Clicking a bookmark in the new UI doesn't scroll to the event card in Chrome.
- The bookmark JPG needs to be updated so that it matches the UI.
- A tab other than the one you are currently on is highlighted when first opening the bookmark UI. It seems to change between page refreshes.
- I'm torn on the use of different stars for the different types of progress bookmarks. I think its useful to differentiate between starting, progressing, and completing. However this could potentially be confusing to some as the other icons correspond to the tabs that sort them (it looks like they are another category of bookmark). I think the text that you've prepended to the bookmark is clear enough and changing the other stages to an un-filled star would be best.
- I think it would be slick if after clicking a bookmark, the card flashed/highlighted in some way. Currently if the scrollbar doesn't move, its not obvious which event card is the one of interest. I think it would be fine left for a later improvement, but figured I'd include it in case you wanted to tackle it now.

Cheers!

**Comment by cilestin** [comment]
@SHiLLySiT Changes made & commits squashed. Fixing the chrome bug was tougher than I expected!

**Comment by SHiLLySiT** [comment]
@cilestin Derp, I just noticed you had other icons for meta vs fiction and bond vs unbond. I think having the half filled and full stars for progress makes total sense now. Before I was just concerned because I thought it was the only bookmark type that did that! Apologies!

**Comment by cilestin** [comment]
@SHiLLySiT No worries! Reverted the icon change and made a new screenshot for the docs 👍

**Pull request merged**
